# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:

- task: UiPathRunJob@4
  displayName: 'Setting up the test environment'
  inputs:
    orchestratorConnection: 'TestSuiteDevOpsAtScale'
    processName: 'AppServerCreate'
    folderName: 'InternalDemos/TSDO_TestSuite_DevOps_AtScale'
 
- task: UiPathTest@4
  displayName: 'Running functional tests'
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'TestSuiteDevOpsAtScale'
    testSet: 'UiBank Regression'
    folderName: 'InternalDemos/TSDO_TestSuite_DevOps_AtScale'
    
- task: UiPathRunJob@4
  displayName: 'Cleaning up the test environment'
  continueOnError: true 
  inputs:
    orchestratorConnection: 'TestSuiteDevOpsAtScale'
    processName: 'AppServerDelete'
    folderName: 'InternalDemos/TSDO_TestSuite_DevOps_AtScale'